# Generated by Django 3.0.5 on 2020-05-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_categorytable_doctorstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=60)),
                ('appoint_date', models.DateField()),
                ('appoint_time', models.TimeField()),
                ('dr_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DoctorsTable')),
            ],
        ),
    ]
